services:
  backend:
    image: renansis/hello-world-java:1.0
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: ./
    ports:
      - "4200:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
